server.port=8082
spring.application.name=thread-pool-monitor

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.jmx.enabled=true

management.endpoints.web.exposure.include=health,info,metrics
